-- =============================================================================
-- Migración 00081 — Módulos de Dietas y Provisión Social
-- Cooperativa Primero de Mayo · SistemaCooperativa
-- -----------------------------------------------------------------------------
-- Crea la tabla para registrar beneficios entregados a los socios:
-- - Dietas (por ejemplo: asistencia a asambleas, reuniones).
-- - Provisión Social (por ejemplo: apoyo por salud, luto, etc.).
-- =============================================================================

create table if not exists public.beneficios_socios (
    id bigint generated by default as identity primary key,
    socio_id bigint references public.socios(id) not null,
    tipo text not null check (tipo in ('dieta', 'provision_social')),
    fecha date not null,
    monto numeric(10,2) not null check (monto > 0),
    motivo text,
    observacion text,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    created_by uuid references auth.users(id),
    deleted_at timestamp with time zone,
    deleted_by uuid references auth.users(id)
);

-- Índices para búsquedas rápidas (por socio y por año para reportes)
create index if not exists idx_beneficios_socios_socio on public.beneficios_socios(socio_id);
create index if not exists idx_beneficios_socios_tipo_fecha on public.beneficios_socios(tipo, fecha);

-- Habilitar RLS
alter table public.beneficios_socios enable row level security;

-- Políticas: Solo Administrador y Caja pueden ver y gestionar beneficios
create policy "Administradores y Caja pueden ver beneficios"
    on public.beneficios_socios
    for select
    using (public.get_my_rol() in ('Administrador', 'Caja') and deleted_at is null);

create policy "Administradores y Caja pueden insertar beneficios"
    on public.beneficios_socios
    for insert
    with check (public.get_my_rol() in ('Administrador', 'Caja'));

create policy "Administradores y Caja pueden actualizar beneficios"
    on public.beneficios_socios
    for update
    using (public.get_my_rol() in ('Administrador', 'Caja'));

create policy "Administradores y Caja pueden eliminar (soft delete)"
    on public.beneficios_socios
    for delete
    using (public.get_my_rol() in ('Administrador', 'Caja'));

-- Comentarios
comment on table public.beneficios_socios is 'Registro de dietas y ayudas de provisión social entregadas a los socios.';
comment on column public.beneficios_socios.tipo is 'Clasificación: dieta o provision_social.';
comment on column public.beneficios_socios.motivo is 'Concepto principal o razón de la entrega.';
